on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
     - name: Criado diretório
        run: |
          mkdir web/global/
        run: |
          mkdir web/pages/
    - uses: canastro/copy-file-action@master
        with:
          source: "web/global/GlobalKeywords.robot"
          target: "web/global"
          source: "web/pages/Login.robot"
          target: "web/pages/"
          source: "web/pages/Movimentacao.robot"
          target: "web/pages/"    
    - uses: actions/checkout@v2
    - uses: actions/checkout@master
      - name: Rodando Testes
    - uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_tests_dir: web/testes